version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-96-169.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: dfvr8fmllitsp8
            ssl: true
            user: bmcwyxjmdcpcmf
            password: 6193b65b4a9da4d68fad67254895aa7a4aed9d5800a050d8dd9bb592dd0c02c2
            migrations: true
